// ============================================================
// CATÁLOGO DE PRODUCTOS - BELLO MERCADO
// 150+ productos organizados por categoría
// Precios en pesos uruguayos (UYU)
// ============================================================

export const CATEGORIES = [
  { id: 'todo', label: 'Todo', image: '/images/vegetables.png' },
  { id: 'carniceria', label: 'Carnicería', image: '/images/meat.png' },
  { id: 'fiambreria', label: 'Fiambrería', image: '/images/deli.png' },
  { id: 'pollos', label: 'Pollos y Aves', image: '/images/poultry.png' },
  { id: 'cerdo', label: 'Cerdo', image: '/images/pork.png' },
  { id: 'pescados', label: 'Pescados y Mariscos', image: '/images/fish.png' },
  { id: 'verduras', label: 'Verduras y Frutas', image: '/images/vegetables.png' },
  { id: 'lacteos', label: 'Lácteos y Huevos', image: '/images/dairy.png' },
  { id: 'bebidas', label: 'Bebidas', image: '/images/beverages.png' },
  { id: 'envasados', label: 'Envasados y Almacén', image: '/images/packaged.png' },
  { id: 'panaderia', label: 'Panadería', image: '/images/bakery.png' },
  { id: 'congelados', label: 'Congelados', image: '/images/frozen.png' },
  { id: 'limpieza', label: 'Limpieza', image: '/images/cleaning.png' },
  { id: 'higiene', label: 'Higiene Personal', image: '/images/hygiene.png' },
  { id: 'lenya', label: 'Leña y Carbón', image: '/images/charcoal.png' },
];

export const PRODUCTS = [
  // ===================== CARNICERÍA =====================
  { id: 1,   name: 'Asado de Tira',          price: 390,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 2,   name: 'Vacío',                   price: 420,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 3,   name: 'Colita de Cuadril',       price: 490,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 4,   name: 'Cuadril Entero',          price: 520,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 5,   name: 'Entrecot / Bife de Lomo', price: 680,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 6,   name: 'Lomo',                    price: 850,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 7,   name: 'Paleta',                  price: 310,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 8,   name: 'Aguja',                   price: 270,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 9,   name: 'Ossobuco',                price: 280,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 10,  name: 'Osobuco de Cerdo',        price: 260,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 11,  name: 'Carnaza',                 price: 250,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 12,  name: 'Milanesas de Carne',      price: 390,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 13,  name: 'Carne Picada',            price: 300,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 14,  name: 'Mondongo',                price: 200,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 15,  name: 'Riñones',                 price: 180,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 16,  name: 'Chinchulines',            price: 220,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 17,  name: 'Mollejas',                price: 350,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 18,  name: 'Morcilla',                price: 280,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 19,  name: 'Costillas Vacuna',        price: 340,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },
  { id: 20,  name: 'Bife Ancho',              price: 590,  unit: 'kg', category: 'carniceria',  image: '/images/meat.png' },

  // ===================== FIAMBRERÍA =====================
  { id: 21,  name: 'Chorizos Caseros',        price: 360,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 22,  name: 'Salame Tipo Milano',      price: 580,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 23,  name: 'Jamón Cocido',            price: 420,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 24,  name: 'Jamón Crudo',             price: 650,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 25,  name: 'Mortadela',               price: 320,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 26,  name: 'Paleta Cocida',           price: 380,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 27,  name: 'Lomito Ahumado',          price: 720,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 28,  name: 'Queso Feta',              price: 540,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 29,  name: 'Queso Colonia',           price: 480,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 30,  name: 'Queso Dambo',             price: 450,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 31,  name: 'Queso Parmesano',         price: 680,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 32,  name: 'Queso Mozzarella',        price: 510,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 33,  name: 'Salchichas Frankfurt',    price: 290,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 34,  name: 'Pastrami',                price: 780,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },
  { id: 35,  name: 'Prosciutto',              price: 920,  unit: 'kg', category: 'fiambreria',  image: '/images/deli.png' },

  // ===================== POLLOS Y AVES =====================
  { id: 36,  name: 'Pollo Entero',            price: 185,  unit: 'kg', category: 'pollos',      image: '/images/poultry.png' },
  { id: 37,  name: 'Pechuga de Pollo',        price: 290,  unit: 'kg', category: 'pollos',      image: '/images/poultry.png' },
  { id: 38,  name: 'Muslo de Pollo',          price: 220,  unit: 'kg', category: 'pollos',      image: '/images/poultry.png' },
  { id: 39,  name: 'Alitas de Pollo',         price: 210,  unit: 'kg', category: 'pollos',      image: '/images/poultry.png' },
  { id: 40,  name: 'Milanesas de Pollo',      price: 310,  unit: 'kg', category: 'pollos',      image: '/images/poultry.png' },
  { id: 41,  name: 'Suprema de Pollo',        price: 330,  unit: 'kg', category: 'pollos',      image: '/images/poultry.png' },
  { id: 42,  name: 'Corazones de Pollo',      price: 190,  unit: 'kg', category: 'pollos',      image: '/images/poultry.png' },
  { id: 43,  name: 'Pato Entero',             price: 420,  unit: 'kg', category: 'pollos',      image: '/images/poultry.png' },

  // ===================== CERDO =====================
  { id: 44,  name: 'Bondiola de Cerdo',       price: 330,  unit: 'kg', category: 'cerdo',       image: '/images/pork.png' },
  { id: 45,  name: 'Costillas de Cerdo',      price: 310,  unit: 'kg', category: 'cerdo',       image: '/images/pork.png' },
  { id: 46,  name: 'Lomo de Cerdo',           price: 380,  unit: 'kg', category: 'cerdo',       image: '/images/pork.png' },
  { id: 47,  name: 'Panceta Fresca',          price: 290,  unit: 'kg', category: 'cerdo',       image: '/images/pork.png' },
  { id: 48,  name: 'Panceta Ahumada',         price: 360,  unit: 'kg', category: 'cerdo',       image: '/images/pork.png' },
  { id: 49,  name: 'Pernil de Cerdo',         price: 340,  unit: 'kg', category: 'cerdo',       image: '/images/pork.png' },
  { id: 50,  name: 'Chuletas de Cerdo',       price: 320,  unit: 'kg', category: 'cerdo',       image: '/images/pork.png' },

  // ===================== PESCADOS =====================
  { id: 51,  name: 'Filete de Merluza',       price: 380,  unit: 'kg', category: 'pescados',    image: '/images/fish.png' },
  { id: 52,  name: 'Lenguado Fresco',         price: 490,  unit: 'kg', category: 'pescados',    image: '/images/fish.png' },
  { id: 53,  name: 'Camarones',               price: 620,  unit: 'kg', category: 'pescados',    image: '/images/fish.png' },
  { id: 54,  name: 'Mejillones',              price: 280,  unit: 'kg', category: 'pescados',    image: '/images/fish.png' },
  { id: 55,  name: 'Atún en Lata (x3)',       price: 210,  unit: 'un', category: 'pescados',    image: '/images/fish.png' },
  { id: 56,  name: 'Sardinas en Aceite',      price: 95,   unit: 'un', category: 'pescados',    image: '/images/fish.png' },

  // ===================== VERDURAS Y FRUTAS =====================
  { id: 57,  name: 'Papa (bolsa 5kg)',         price: 210,  unit: 'un', category: 'verduras',    image: '/images/vegetables.png' },
  { id: 58,  name: 'Cebolla (bolsa 2kg)',      price: 115,  unit: 'un', category: 'verduras',    image: '/images/vegetables.png' },
  { id: 59,  name: 'Ajo (cabeza)',             price: 45,   unit: 'un', category: 'verduras',    image: '/images/vegetables.png' },
  { id: 60,  name: 'Zanahoria (kg)',           price: 80,   unit: 'kg', category: 'verduras',    image: '/images/vegetables.png' },
  { id: 61,  name: 'Tomate (kg)',              price: 120,  unit: 'kg', category: 'verduras',    image: '/images/vegetables.png' },
  { id: 62,  name: 'Limón (bolsa)',            price: 90,   unit: 'un', category: 'verduras',    image: '/images/vegetables.png' },
  { id: 63,  name: 'Lechuga (un)',             price: 65,   unit: 'un', category: 'verduras',    image: '/images/vegetables.png' },
  { id: 64,  name: 'Pimiento Rojo',            price: 95,   unit: 'kg', category: 'verduras',    image: '/images/vegetables.png' },
  { id: 65,  name: 'Manzana (kg)',             price: 130,  unit: 'kg', category: 'verduras',    image: '/images/vegetables.png' },
  { id: 66,  name: 'Naranja (kg)',             price: 90,   unit: 'kg', category: 'verduras',    image: '/images/vegetables.png' },
  { id: 67,  name: 'Banana (kg)',              price: 75,   unit: 'kg', category: 'verduras',    image: '/images/vegetables.png' },

  // ===================== LÁCTEOS Y HUEVOS =====================
  { id: 68,  name: 'Leche Entera (1L)',        price: 65,   unit: 'un', category: 'lacteos',     image: '/images/dairy.png' },
  { id: 69,  name: 'Leche Descremada (1L)',    price: 68,   unit: 'un', category: 'lacteos',     image: '/images/dairy.png' },
  { id: 70,  name: 'Yogur Natural (200g)',     price: 70,   unit: 'un', category: 'lacteos',     image: '/images/dairy.png' },
  { id: 71,  name: 'Manteca (200g)',           price: 145,  unit: 'un', category: 'lacteos',     image: '/images/dairy.png' },
  { id: 72,  name: 'Crema de Leche (200ml)',   price: 120,  unit: 'un', category: 'lacteos',     image: '/images/dairy.png' },
  { id: 73,  name: 'Huevos Blancos (doc.)',    price: 185,  unit: 'un', category: 'lacteos',     image: '/images/dairy.png' },
  { id: 74,  name: 'Huevos Marrones (doc.)',   price: 195,  unit: 'un', category: 'lacteos',     image: '/images/dairy.png' },

  // ===================== BEBIDAS =====================
  { id: 75,  name: 'Agua Mineral (1.5L)',      price: 80,   unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 76,  name: 'Agua c/Gas (1.5L)',        price: 85,   unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 77,  name: 'Coca-Cola (2.25L)',        price: 195,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 78,  name: 'Coca-Cola (500ml)',        price: 95,   unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 79,  name: 'Pepsi (2L)',               price: 175,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 80,  name: 'Sprite (2L)',              price: 175,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 81,  name: 'Fanta Naranja (2L)',       price: 175,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 82,  name: 'Jugo Tang (sobre)',        price: 45,   unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 83,  name: 'Cerveza Patricia (1L)',    price: 145,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 84,  name: 'Cerveza Pilsen (lata)',    price: 95,   unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 85,  name: 'Cerveza Amstel (6-pack)',  price: 590,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 86,  name: 'Vino Tinto (750ml)',       price: 420,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 87,  name: 'Vino Blanco (750ml)',      price: 390,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 88,  name: 'Sidra Don Valentin (750)', price: 330,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 89,  name: 'Whisky Etiqueta Roja',     price: 1290, unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 90,  name: 'Ron Bacardí (750ml)',      price: 980,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 91,  name: 'Té (caja 25 saquitos)',    price: 145,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 92,  name: 'Yerba Mate (1kg)',         price: 380,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },
  { id: 93,  name: 'Café Molido (250g)',       price: 290,  unit: 'un', category: 'bebidas',     image: '/images/beverages.png' },

  // ===================== ENVASADOS Y ALMACÉN =====================
  { id: 94,  name: 'Arroz (1kg)',              price: 115,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 95,  name: 'Arroz Integral (1kg)',     price: 135,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 96,  name: 'Fideos Espagueti (500g)',  price: 85,   unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 97,  name: 'Fideos Corbata (500g)',    price: 85,   unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 98,  name: 'Harina 0000 (1kg)',        price: 95,   unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 99,  name: 'Azúcar (1kg)',             price: 110,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 100, name: 'Sal Fina (500g)',          price: 55,   unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 101, name: 'Aceite de Girasol (1L)',   price: 175,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 102, name: 'Aceite de Oliva (500ml)',  price: 490,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 103, name: 'Vinagre de Manzana',       price: 130,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 104, name: 'Salsa de Tomate (400g)',   price: 110,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 105, name: 'Pasta de Tomate (200g)',   price: 80,   unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 106, name: 'Mayonesa (500g)',          price: 210,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 107, name: 'Ketchup (500g)',           price: 195,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 108, name: 'Mostaza (200g)',           price: 150,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 109, name: 'Chimichurri (200ml)',      price: 185,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 110, name: 'Salsa Criolla (lata)',     price: 120,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 111, name: 'Lentejas (500g)',          price: 115,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 112, name: 'Garbanzos (500g)',         price: 120,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 113, name: 'Arvejas (400g lata)',      price: 95,   unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 114, name: 'Choclo (400g lata)',       price: 105,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 115, name: 'Galletitas Saladas (200g)',price: 130,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 116, name: 'Galletitas Dulces (200g)', price: 145,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 117, name: 'Papas Fritas (150g)',      price: 165,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 118, name: 'Maizena (500g)',           price: 140,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },
  { id: 119, name: 'Pan Rallado (500g)',       price: 115,  unit: 'un', category: 'envasados',   image: '/images/packaged.png' },

  // ===================== PANADERÍA =====================
  { id: 120, name: 'Pan de Mesa (500g)',       price: 120,  unit: 'un', category: 'panaderia',   image: '/images/bakery.png' },
  { id: 121, name: 'Pan Lactal (720g)',        price: 195,  unit: 'un', category: 'panaderia',   image: '/images/bakery.png' },
  { id: 122, name: 'Pan de Hamburguesa (x4)',  price: 135,  unit: 'un', category: 'panaderia',   image: '/images/bakery.png' },
  { id: 123, name: 'Pan Árabe (x5)',           price: 125,  unit: 'un', category: 'panaderia',   image: '/images/bakery.png' },
  { id: 124, name: 'Pan Francés (x6)',         price: 145,  unit: 'un', category: 'panaderia',   image: '/images/bakery.png' },
  { id: 125, name: 'Facturas (x6)',            price: 290,  unit: 'un', category: 'panaderia',   image: '/images/bakery.png' },
  { id: 126, name: 'Bizcochos (x6)',           price: 210,  unit: 'un', category: 'panaderia',   image: '/images/bakery.png' },

  // ===================== CONGELADOS =====================
  { id: 127, name: 'Hamburguesas x4 (500g)',   price: 390,  unit: 'un', category: 'congelados',  image: '/images/frozen.png' },
  { id: 128, name: 'Papas Pre-fritas (1kg)',   price: 280,  unit: 'un', category: 'congelados',  image: '/images/frozen.png' },
  { id: 129, name: 'Supremas Rebozadas (x4)',  price: 410,  unit: 'un', category: 'congelados',  image: '/images/frozen.png' },
  { id: 130, name: 'Pizza Congelada (muzz.)',  price: 450,  unit: 'un', category: 'congelados',  image: '/images/frozen.png' },
  { id: 131, name: 'Empanadas Carne (x12)',    price: 520,  unit: 'un', category: 'congelados',  image: '/images/frozen.png' },
  { id: 132, name: 'Helado Familiar (1L)',     price: 490,  unit: 'un', category: 'congelados',  image: '/images/frozen.png' },
  { id: 133, name: 'Chorizos Congelados (kg)', price: 340,  unit: 'kg', category: 'congelados',  image: '/images/frozen.png' },

  // ===================== LIMPIEZA =====================
  { id: 134, name: 'Detergente (500ml)',       price: 135,  unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 135, name: 'Lavandina (2L)',           price: 165,  unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 136, name: 'Limpiapisos (1L)',         price: 195,  unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 137, name: 'Desengrasante (500ml)',    price: 185,  unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 138, name: 'Jabón en Polvo (1kg)',     price: 290,  unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 139, name: 'Suavizante (1L)',          price: 250,  unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 140, name: 'Bolsas Basura x10',        price: 120,  unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 141, name: 'Papel Higiénico (x4)',     price: 220,  unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 142, name: 'Esponja Dual x2',          price: 95,   unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 143, name: 'Trapos de Piso x2',        price: 145,  unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 144, name: 'Limpiavidrios (500ml)',    price: 170,  unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },
  { id: 145, name: 'Bala de Gas (10kg)',       price: 1450, unit: 'un', category: 'limpieza',    image: '/images/cleaning.png' },

  // ===================== HIGIENE PERSONAL =====================
  { id: 146, name: 'Shampoo (400ml)',          price: 290,  unit: 'un', category: 'higiene',     image: '/images/hygiene.png' },
  { id: 147, name: 'Acondicionador (400ml)',   price: 295,  unit: 'un', category: 'higiene',     image: '/images/hygiene.png' },
  { id: 148, name: 'Jabón de Tocador x3',      price: 165,  unit: 'un', category: 'higiene',     image: '/images/hygiene.png' },
  { id: 149, name: 'Pasta Dental (90ml)',      price: 145,  unit: 'un', category: 'higiene',     image: '/images/hygiene.png' },
  { id: 150, name: 'Cepillo de Dientes',       price: 110,  unit: 'un', category: 'higiene',     image: '/images/hygiene.png' },
  { id: 151, name: 'Desodorante Spray (150ml)',price: 280,  unit: 'un', category: 'higiene',     image: '/images/hygiene.png' },
  { id: 152, name: 'Afeitadora Descartable',   price: 195,  unit: 'un', category: 'higiene',     image: '/images/hygiene.png' },
  { id: 153, name: 'Crema de Afeitar (100ml)', price: 210,  unit: 'un', category: 'higiene',     image: '/images/hygiene.png' },
  { id: 154, name: 'Algodón (50g)',            price: 120,  unit: 'un', category: 'higiene',     image: '/images/hygiene.png' },
  { id: 155, name: 'Toallas Femeninas x8',     price: 240,  unit: 'un', category: 'higiene',     image: '/images/hygiene.png' },

  // ===================== LEÑA Y CARBÓN =====================
  { id: 156, name: 'Leña (Bolsa grande)',      price: 290,  unit: 'un', category: 'lenya',       image: '/images/charcoal.png' },
  { id: 157, name: 'Leña (Bolsa chica)',       price: 150,  unit: 'un', category: 'lenya',       image: '/images/charcoal.png' },
  { id: 158, name: 'Carbón (Bolsa 3kg)',       price: 245,  unit: 'un', category: 'lenya',       image: '/images/charcoal.png' },
  { id: 159, name: 'Carbón Premium (5kg)',     price: 390,  unit: 'un', category: 'lenya',       image: '/images/charcoal.png' },
  { id: 160, name: 'Pastillas Encendedor x6',  price: 120,  unit: 'un', category: 'lenya',       image: '/images/charcoal.png' },
];

export default PRODUCTS;
